name: Android APK (Manual, Qt 6.6.3)

on:
  workflow_dispatch:    # manual trigger only

jobs:
  build-android:
    runs-on: ubuntu-22.04

    env:
      QT_VERSION: "6.6.3"
      ANDROID_API: "33"
      ANDROID_NDK_VERSION: "25.2.9519653"           # r25c (Qt 6.6.x compatible)
      ANDROID_SDK_ROOT: "${{ github.workspace }}/android-sdk"
      ANDROID_HOME: "${{ github.workspace }}/android-sdk"
      NDK_ROOT: "${{ github.workspace }}/android-sdk/ndk/25.2.9519653"
      ANDROID_NDK_HOME: "${{ github.workspace }}/android-sdk/ndk/25.2.9519653"
      BUILD_DIR: build-android
      QT_HOST_KIT: "gcc_64"
      QT_ANDROID_KIT: "android_arm64_v8a"
      QT_BASE_URL: "https://download.qt.io"

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build python3-pip unzip zip curl
          python3 -m pip install --upgrade "aqtinstall>=3.3.0"

      - name: Install Android SDK + NDK r25c
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"

          # Make sure sdkmanager is on PATH for this step and later ones
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"

          yes | sdkmanager --licenses
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-${ANDROID_API}" \
            "build-tools;34.0.0" \
            "ndk;${ANDROID_NDK_VERSION}"

          # Helpful PATH exports for subsequent steps
          echo "PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH" >> $GITHUB_ENV

      - name: Install Qt 6.6.3 (host + Android kits)
        run: |
          set -e
          mkdir -p $HOME/Qt

          # Host (desktop) kit
          for i in 1 2 3; do aqt install-qt --base "${QT_BASE_URL}" linux desktop ${QT_VERSION} ${QT_HOST_KIT} --outputdir $HOME/Qt && break || sleep 10; done

          # Android kit (+ modules QGC typically needs)
          for i in 1 2 3; do \
            aqt install-qt --base "${QT_BASE_URL}" linux android ${QT_VERSION} ${QT_ANDROID_KIT} --outputdir $HOME/Qt \
              -m qtserialport qtlocation qtpositioning qtsvg qtimageformats qtconnectivity qtshadertools qtquickcontrols2 qt5compat \
            && break || sleep 10; \
          done

          echo "QT_HOST_PATH=$HOME/Qt/${QT_VERSION}/${QT_HOST_KIT}" >> $GITHUB_ENV
          echo "QT_ANDROID_PATH=$HOME/Qt/${QT_VERSION}/${QT_ANDROID_KIT}" >> $GITHUB_ENV

      - name: Print env & key paths (diagnostics)
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "NDK_ROOT=$NDK_ROOT"
          echo "Qt host: $HOME/Qt/${QT_VERSION}/${QT_HOST_KIT}"
          echo "Qt android: $HOME/Qt/${QT_VERSION}/${QT_ANDROID_KIT}"
          cmake --version || true
          ninja --version || true
          ls -la "$HOME/Qt/${QT_VERSION}" || true
          ls -la "$HOME/Qt/${QT_VERSION}/${QT_HOST_KIT}/bin" || true
          ls -la "$HOME/Qt/${QT_VERSION}/${QT_ANDROID_KIT}/bin" || true

      - name: Configure (Android arm64-v8a) via qt-cmake
        env:
          QT_HOST_PATH: ${{ env.QT_HOST_PATH }}
          QT_ANDROID_PATH: ${{ env.QT_ANDROID_PATH }}
        run: |
          set -e
          export QT_HOST_PATH="${QT_HOST_PATH:-$HOME/Qt/${QT_VERSION}/${QT_HOST_KIT}}"
          export QT_ANDROID_PATH="${QT_ANDROID_PATH:-$HOME/Qt/${QT_VERSION}/${QT_ANDROID_KIT}}"

          echo "QT_HOST_PATH=${QT_HOST_PATH}"
          echo "QT_ANDROID_PATH=${QT_ANDROID_PATH}"

          # Ensure Qt host bin on PATH so lrelease, rcc, etc. are discoverable
          export PATH="$QT_HOST_PATH/bin:$PATH"

          # Use Qt's wrapper to help CMake find the right Qt6 packages
          set -o pipefail
          "$QT_HOST_PATH/bin/qt-cmake" -S . -B "${BUILD_DIR}" -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D ANDROID=ON \
            -D ANDROID_ABI=arm64-v8a \
            -D ANDROID_PLATFORM=android-${ANDROID_API} \
            -D ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT}" \
            -D ANDROID_NDK_ROOT="${NDK_ROOT}" \
            -D QT_HOST_PATH="${QT_HOST_PATH}" \
            -D CMAKE_TOOLCHAIN_FILE="${NDK_ROOT}/build/cmake/android.toolchain.cmake" \
            -D CMAKE_FIND_ROOT_PATH="${QT_ANDROID_PATH}" \
            -D CMAKE_PREFIX_PATH="${QT_ANDROID_PATH};${QT_HOST_PATH}" \
            2>&1 | tee configure.log
          STATUS=${PIPESTATUS[0]}
          if [ $STATUS -ne 0 ]; then
            echo "------ CMakeError.log ------" || true
            cat "${BUILD_DIR}/CMakeFiles/CMakeError.log" || true
            echo "------ tail CMakeOutput.log ------" || true
            tail -n 200 "${BUILD_DIR}/CMakeFiles/CMakeOutput.log" || true
            exit $STATUS
          fi

      - name: Build (verbose)
        run: |
          cmake --build "${BUILD_DIR}" --config Release -- -v

      - name: Package APK & list outputs
        run: |
          cmake --build "${BUILD_DIR}" --target apk || true
          echo "Searching for APK/AAB outputs..."
          find "${BUILD_DIR}" -type d -iname "android-build" -print || true
          find "${BUILD_DIR}" -name "*.apk" -print || true
          find "${BUILD_DIR}" -name "*.aab" -print || true

      - name: Upload APK/AAB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qgroundcontrol-android
          path: |
            ${BUILD_DIR}/**/android-build/**/*.apk
            ${BUILD_DIR}/**/*.apk
            ${BUILD_DIR}/**/*.aab
          if-no-files-found: warn