name: Android APK (manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to build (e.g. master, feat/stabilizer, v4.5.10)"
        required: true
        default: "master"
      abis:
        description: "Android ABIs"
        required: true
        default: "arm64-v8a"
      qt_version:
        description: "Qt version"
        required: true
        default: "5.15.2"
      ndk_version:
        description: "Android NDK version"
        required: true
        default: "21.3.6528147"
      sdk_platform:
        description: "Android SDK platform"
        required: true
        default: "android-30"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-android:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/Android

    steps:
      - name: Checkout (with submodules) at ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name || github.event.repository.default_branch }}
          submodules: recursive
          fetch-depth: 0

      # Use Java 17 so sdkmanager runs correctly
      - name: Set up Java 17 (for sdkmanager)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}
          key: ${{ runner.os }}-android-${{ inputs.sdk_platform }}-ndk-${{ inputs.ndk_version }}
          restore-keys: |
            ${{ runner.os }}-android-

      - name: Install Android cmdline-tools
        uses: android-actions/setup-android@v3

      - name: Install SDK components + accept licenses (robust)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          export PATH="$JAVA_HOME/bin:$PATH"
          mkdir -p "$ANDROID_SDK_ROOT"

          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;${{ inputs.sdk_platform }}" \
            "build-tools;30.0.3" \
            "ndk;${{ inputs.ndk_version }}" \
            "cmdline-tools;latest"

          # Avoid failing the step when 'yes' gets SIGPIPE after sdkmanager exits.
          set +o pipefail
          yes 2>/dev/null | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses >/dev/null || true

      # Switch to Java 11 for Qt5/Gradle
      - name: Switch to Java 11 (for Qt5/Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: gradle

      - name: Install Qt (with Android)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ inputs.qt_version }}
          host: linux
          target: android
          cache: true
          # modules: qtimageformats

      - name: Configure (qmake)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          mkdir -p build-android
          pushd build-android
          "${HOME}/Qt/${{ inputs.qt_version }}/android/bin/qmake" -r ../qgroundcontrol.pro -spec android-clang \
            CONFIG+=release ANDROID_ABIS="${{ inputs.abis }}"
          popd

      - name: Build
        run: |
          pushd build-android
          make -j"$(nproc)"
          popd

      - name: Package APK (assembleRelease)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          export PATH="$JAVA_HOME/bin:$PATH"   # Ensure Java 11 on PATH for Gradle
          pushd build-android/android-build
          ./gradlew --no-daemon --warning-mode=all assembleRelease
          popd

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: qgc-apk-${{ github.event.inputs.ref || github.ref_name }}
          path: build-android/android-build/app/build/outputs/apk/release/*.apk
