name: Android Build (manual)

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.6.3
  ANDROID_API: 33
  ANDROID_NDK_VERSION: 25.2.9519653
  BUILD_DIR: build-android
  QT_HOST_KIT: gcc_64
  QT_ANDROID_KIT: android_arm64_v8a
  QT_BASE_URL: https://download.qt.io

jobs:
  android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install aqtinstall and deps
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall==3.3.0

      - name: Install Android SDK + NDK
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT"
          yes | sudo ${ANDROID_HOME:-/usr/local/lib/android/sdk}/cmdline-tools/latest/bin/sdkmanager --licenses || true
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platforms;android-${{ env.ANDROID_API }}" \
            "build-tools;34.0.0" \
            "platform-tools" \
            "ndk;${{ env.ANDROID_NDK_VERSION }}"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "NDK_ROOT=$ANDROID_SDK_ROOT/ndk/${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV

      - name: Install Qt (host + android)
        env:
          QT_VERSION: ${{ env.QT_VERSION }}
          QT_HOST_KIT: ${{ env.QT_HOST_KIT }}
          QT_ANDROID_KIT: ${{ env.QT_ANDROID_KIT }}
        run: |
          set -e
          mkdir -p $HOME/Qt

          # Host Qt: do NOT request qttools for this combo (it’s not listed for 6.6.3/linux/gcc_64 via aqt)
          aqt install-qt linux desktop ${QT_VERSION} ${QT_HOST_KIT} --outputdir $HOME/Qt

          # Android Qt: keep the modules QGC needs
          aqt install-qt linux android ${QT_VERSION} ${QT_ANDROID_KIT} --outputdir $HOME/Qt \
            -m qtserialport qtlocation qtpositioning qtsvg qtimageformats qtconnectivity qtshadertools qtquickcontrols2 qt5compat

          echo "QT_HOST_PATH=$HOME/Qt/${QT_VERSION}/${QT_HOST_KIT}" >> $GITHUB_ENV
          echo "QT_ANDROID_PATH=$HOME/Qt/${QT_VERSION}/${QT_ANDROID_KIT}" >> $GITHUB_ENV

      - name: Configure (CMake)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          NDK_ROOT: ${{ env.NDK_ROOT }}
          QT_HOST_PATH: ${{ env.QT_HOST_PATH }}
          QT_ANDROID_PATH: ${{ env.QT_ANDROID_PATH }}
          BUILD_DIR: ${{ env.BUILD_DIR }}
          ANDROID_API: ${{ env.ANDROID_API }}
        run: |
          set -e
          echo "QT_HOST_PATH=${QT_HOST_PATH}"
          echo "QT_ANDROID_PATH=${QT_ANDROID_PATH}"

          cmake -S . -B "${BUILD_DIR}" -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D ANDROID=ON \
            -D ANDROID_ABI=arm64-v8a \
            -D ANDROID_PLATFORM=android-${ANDROID_API} \
            -D ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT}" \
            -D ANDROID_NDK_ROOT="${NDK_ROOT}" \
            -D QT_HOST_PATH="${QT_HOST_PATH}" \
            -D CMAKE_TOOLCHAIN_FILE="${NDK_ROOT}/build/cmake/android.toolchain.cmake" \
            -D CMAKE_FIND_ROOT_PATH="${QT_ANDROID_PATH}" \
            -D CMAKE_PREFIX_PATH="${QT_ANDROID_PATH};${QT_HOST_PATH}"

      - name: Build (Ninja)
        run: |
          ninja -C "${BUILD_DIR}"

      - name: Package APK/AAB (if applicable)
        run: |
          # Add your packaging step here if needed
          echo "Packaging placeholder"