name: Android (Qt 6.8.3)

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/android_qt683.yml"

permissions:
  contents: read

jobs:
  build-android:
    name: Build Android (arm64-v8a)
    runs-on: ubuntu-22.04

    env:
      ANDROID_API: "34"
      BUILD_DIR: build-android

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses & install platforms
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-${ANDROID_API}" "build-tools;34.0.0"

      - name: Setup Android NDK (r27c)
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          add-to-path: true

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      # Qt for Android (arm64) – only modules that exist for Android
      - name: Install Qt 6.8.3 (Android arm64-v8a)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          host: linux
          target: android
          arch: android_arm64_v8a
          modules: qtserialport qtlocation qtpositioning qtimageformats qtconnectivity qtshadertools
          cache: true

      # Host Qt to provide host tools expected by CMake/Qt
      - name: Install Qt 6.8.3 (Host gcc_64)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          host: linux
          target: desktop
          arch: gcc_64
          cache: true

      - name: Show Qt variables (sanity check)
        run: |
          echo "Qt6_DIR=${Qt6_DIR}"
          echo "QTDIR=${QTDIR}"
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"
          echo "ANDROID_NDK_ROOT=${ANDROID_NDK_ROOT}"

      - name: Configure (CMake)
        run: |
          cmake -S . -B ${BUILD_DIR} \
            -G Ninja \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-${ANDROID_API} \
            -DCMAKE_BUILD_TYPE=Release \
            -DQT_ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT" \
            -DQT_ANDROID_NDK_ROOT="$ANDROID_NDK_ROOT" \
            -DQT_HOST_PATH="${Qt6_DIR%/lib/cmake/Qt6}/.."

      - name: Build
        run: cmake --build ${BUILD_DIR} --config Release -j"$(nproc)"

      - name: Package APK/AAB (if targets exist)
        run: |
          cmake --build ${BUILD_DIR} --target apk  || true
          cmake --build ${BUILD_DIR} --target aab  || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-output
          path: |
            ${BUILD_DIR}/**/*.apk
            ${BUILD_DIR}/**/*.aab
          if-no-files-found: warn