name: Android Build (Qt 6.8.3, no aqt)

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/build-android.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_API: "34"
      BUILD_DIR: build-android

    steps:
      - name: Identify this workflow
        run: |
          echo "This is .github/workflows/build-android.yml"
          echo "If you see 'aqtinstall' in logs, another workflow is still running."

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses & install platforms
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-${ANDROID_API}" "build-tools;34.0.0"

      - name: Setup Android NDK r27c
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          add-to-path: true

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      # ---------- Qt for Android (arm64) ----------
      - name: Install Qt 6.8.3 (Android arm64-v8a)
        id: qt_android
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          host: linux
          target: android
          arch: android_arm64_v8a
          # Only modules that exist for Android in 6.8.x
          modules: qtserialport qtlocation qtpositioning qtimageformats qtconnectivity qtshadertools
          cache: true

      - name: Capture Android Qt path
        run: echo "ANDROID_QT_DIR=${QTDIR}" >> $GITHUB_ENV

      # ---------- Host Qt (tools for qt-cmake, rcc, etc.) ----------
      - name: Install Qt 6.8.3 (Host gcc_64)
        id: qt_host
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          host: linux
          target: desktop
          arch: gcc_64
          cache: true

      - name: Capture Host Qt path
        run: echo "QT_HOST_PATH=${QTDIR}" >> $GITHUB_ENV

      - name: Sanity check paths
        run: |
          echo "ANDROID_QT_DIR=${ANDROID_QT_DIR}"
          echo "QT_HOST_PATH=${QT_HOST_PATH}"
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"
          echo "ANDROID_NDK_ROOT=${ANDROID_NDK_ROOT}"

      - name: Configure (qt-cmake)
        run: |
          "${QT_HOST_PATH}/bin/qt-cmake" -S . -B "${BUILD_DIR}" -G Ninja \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-${ANDROID_API} \
            -DQT_ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT}" \
            -DQT_ANDROID_NDK_ROOT="${ANDROID_NDK_ROOT}" \
            -DQT_HOST_PATH="${QT_HOST_PATH}" \
            -DCMAKE_PREFIX_PATH="${ANDROID_QT_DIR}"

      - name: Build
        run: cmake --build "${BUILD_DIR}" --config Release -j"$(nproc)"

      - name: Package (best-effort)
        run: |
          cmake --build "${BUILD_DIR}" --target apk || true
          cmake --build "${BUILD_DIR}" --target aab || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-output
          path: |
            ${BUILD_DIR}/**/*.apk
            ${BUILD_DIR}/**/*.aab
          if-no-files-found: warn