name: Android (Qt 6.8.3)

on:
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-22.04

    env:
      QT_VERSION: "6.8.3"
      ANDROID_API: "34"
      BUILD_DIR: build-android

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses (no broken pipe)
        run: |
          yes | sdkmanager --licenses >/dev/null || true

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-${ANDROID_API}" "build-tools;34.0.0"

      - name: Install NDK r27c
        id: ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Export NDK environment variables
        run: |
          echo "ANDROID_NDK_ROOT=${{ steps.ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "NDK_ROOT=${{ steps.ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      # =========================
      # PYTHON + AQT (fixed)
      # =========================
      - name: Set up Python 3.11 and aqtinstall
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install aqt and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "aqtinstall==3.3.0"

      - name: Log available Qt modules
        run: |
          python -m aqt list-qt linux desktop --modules ${QT_VERSION} gcc_64 || true
          python -m aqt list-qt linux android --modules ${QT_VERSION} android_arm64_v8a || true

      - name: Install Qt (desktop gcc_64)
        env:
          QT_DIR: ${{ github.workspace }}/Qt
        run: |
          mkdir -p "${QT_DIR}"
          python -m aqt install-qt linux desktop ${QT_VERSION} gcc_64 \
            -O "${QT_DIR}" \
            -m qtserialport qtlocation qtpositioning qtsvg qtimageformats qtconnectivity qtshadertools qtquickcontrols2 qt5compat
          echo "QT_HOST_PATH=${QT_DIR}/${QT_VERSION}/gcc_64" >> $GITHUB_ENV

      - name: Install Qt (android arm64)
        env:
          QT_DIR: ${{ github.workspace }}/Qt
        run: |
          python -m aqt install-qt linux android ${QT_VERSION} android_arm64_v8a \
            -O "${QT_DIR}" \
            -m qtserialport qtlocation qtpositioning qtsvg qtimageformats qtconnectivity qtshadertools qtquickcontrols2 qt5compat
          echo "QT_ANDROID_PATH=${QT_DIR}/${QT_VERSION}/android_arm64_v8a" >> $GITHUB_ENV

      - name: Verify Qt setup
        run: |
          echo "QT_HOST_PATH=$QT_HOST_PATH"
          echo "QT_ANDROID_PATH=$QT_ANDROID_PATH"
          "${QT_HOST_PATH}/bin/qt-cmake" --version || true

      - name: Configure CMake for Android
        run: |
          "${QT_ANDROID_PATH}/bin/qt-cmake" -S . -B "${BUILD_DIR}" -G Ninja \
            -DQT_HOST_PATH="${QT_HOST_PATH}" \
            -DCMAKE_BUILD_TYPE=Release \
            -DQT_ANDROID_ABIS=arm64-v8a \
            -DQT_ANDROID_BUILD_ALL_ABIS=OFF \
            -DANDROID_PLATFORM=android-${ANDROID_API} \
            -DANDROID_SDK_ROOT="${ANDROID_SDK_ROOT}" \
            -DANDROID_NDK_ROOT="${ANDROID_NDK_ROOT}"

      - name: Build
        run: cmake --build "${BUILD_DIR}" --parallel

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            ${BUILD_DIR}/**/*.apk
            ${BUILD_DIR}/**/*.aab
            ${BUILD_DIR}/android-build/**/outputs/**/*.apk
            ${BUILD_DIR}/android-build/**/outputs/**/*.aab
          if-no-files-found: warn