name: Android (Qt 6.8.3)

on:
  workflow_dispatch: {}   # enables the “Run workflow” button

permissions:
  contents: read

jobs:
  build-android:
    runs-on: ubuntu-22.04

    env:
      ANDROID_API: "34"
      BUILD_DIR: build-android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-${ANDROID_API}" "build-tools;34.0.0"

      - name: Android NDK r27c
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          add-to-path: true

      # Install Qt for Android with modules (no Python aqt calls)
      - name: Install Qt 6.8.3 (Android)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          host: linux
          target: android
          arch: android_arm64_v8a
          modules: qtserialport qtlocation qtpositioning qtsvg qtimageformats qtconnectivity qtshadertools qtquickcontrols2 qt5compat
          tools: "android"   # ensures android toolchain parts are pulled
          cache: true

      # (Optional) also install host Qt if your build scripts need it
      - name: Install Qt 6.8.3 (Host gcc_64)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          host: linux
          target: desktop
          arch: gcc_64
          cache: true

      - name: Configure (example)
        run: |
          cmake -S . -B ${BUILD_DIR} \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-${ANDROID_API} \
            -DCMAKE_BUILD_TYPE=Release \
            -DQT_HOST_PATH="${Qt6_DIR%/lib/cmake/Qt6}/.." \
            -DQT_ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT" \
            -DQT_ANDROID_NDK_ROOT="$ANDROID_NDK_ROOT"

      - name: Build
        run: cmake --build ${BUILD_DIR} --config Release -j$(nproc)

      # Replace this packaging step with your project’s real one
      - name: Package APK (example)
        run: |
          cmake --build ${BUILD_DIR} --target apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            ${BUILD_DIR}/**/*.apk
            ${BUILD_DIR}/**/*.aab